[workspace]
resolver = "2"
members = [
    "benchmark",
    "quest01",
    "quest02",
    "quest03",
    "quest04",
    "quest05",
    "quest06",
    "quest07",
    "quest08",
    "quest09",
    "quest10", 
    "quest11",
]
