[package]
name = "quest12"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = { version = "0.17.9", features = ["rayon"] }
itertools = "0.13.0"
rayon = "1.10.0"
